# Generated by Django 5.0.7 on 2024-08-03 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_order_id_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
